# Generated by Django 5.2.12 on 2026-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleaccount',
            name='token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
