# Generated by Django 5.2.12 on 2026-04-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='profile_picture',
        ),
    ]
