# Generated by Django 5.2.12 on 2026-04-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
