# Generated by Django 5.2.12 on 2026-04-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='session',
            field=models.JSONField(default=dict),
        ),
    ]
